SERVICE_PORT_ARGUMENT_KEY = 'service_port'
SERVICE_UI_PORT_ARGUMENT_KEY = 'ui_port'
DEFAULT_SERVICE_PORT = 5006
SERVICE_LIFESPAN_HOURS = 6
SERVICE_LIFESPAN_SECONDS = SERVICE_LIFESPAN_HOURS * 3600

DEV=0
VERSION="1.0.4"
